INSERT INTO category(name) values('camiseta');
INSERT INTO category(name) values('vaso');
INSERT INTO category(name) values('comic');
INSERT INTO category(name) values('juguete');
INSERT INTO category(name) values('accesorio');
INSERT INTO users(name, lastname, username, role) VALUES('Maria', 'Perez', 'mari32', 'cajera');
INSERT INTO users(name, lastname, username, role) VALUES('Pedro', 'Ramirez', 'pepe45', 'admin');
INSERT INTO product(name, price, image, stock, category_id) values('Batman V1', 230, 'https://upload.wikimedia.org/wikipedia/en/4/4d/BatmanComicIssue1%2C1940.png', 100, 3);
INSERT INTO product(name, price, image, stock, category_id) VALUES('Mujer Maravilla', 115.0, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvCOipD3cRe10ZsHfBNfNcHdwNpikBMMgxwg&s', 50, 1);
INSERT INTO product(name, price, image, stock, category_id) VALUES('Iron Man', 120.0, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-8F8raXkcRHQKmFqty1LAs2IkUWkbjCP6rA&s', 70, 1);
INSERT INTO product(name, price, image, stock, category_id) VALUES('Batman', 50.0, 'https://upload.wikimedia.org/wikipedia/en/4/4d/BatmanComicIssue1%2C1940.png', 23, 3);
INSERT INTO product(name, price, image, stock, category_id) VALUES('Capitan America', 36.0, 'https://webuniverso.com.ar/wp-content/uploads/2021/02/SP811.jpg', 98, 2);
INSERT INTO product(name, price, image, stock, category_id) VALUES('Llavero Hulk', 60, 'https://i5.walmartimages.com.mx/mg/gm/3pp/asr/febc1ee6-2ed9-4d4b-8970-abe87266a4b4.4d2f8df072b8d2b53db55a3f9800fcc0.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF', 50, 5);
INSERT INTO product(name, price, image, stock, category_id) VALUES('Coleccion Cap', 560, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQt8EkdlfUPPaFvYfY0XGAP9s-E7wfDinzD03ENXuLw8xEW-7xhTiQwapKi3iGJcfu_9mw&usqp=CAU', 40, 4);
INSERT INTO product(name, price, image, stock, category_id) VALUES('Spiderman goma', 238, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8CYIgyB3kmDVGQmvFVkpdsnhdsao4nYo4sA&s', 23, 4);
INSERT INTO product(name, price, image, stock, category_id) VALUES('Llavero Cap', 54.50, 'https://http2.mlstatic.com/D_805920-MLA76025753586_052024-C.jpg', 12, 5);
INSERT INTO product(name, price, image, stock, category_id) VALUES('Llavero escudo', 45, 'https://http2.mlstatic.com/D_NQ_NP_787691-MCO46870764878_072021-O.webp', 200, 5);
INSERT INTO product(name, price, image, stock, category_id) VALUES('Guantes Spiderman', 110, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8iMaaZhcgRZZVST5wQ342IpOiQgY49kQs1Q&s', 102, 5);
INSERT INTO product(name, price, image, stock, category_id) VALUES('Superman animado', 20, 'https://i.etsystatic.com/22889028/r/il/ec105c/2383425697/il_fullxfull.2383425697_n0ra.jpg', 235, 2);
INSERT INTO product(name, price, image, stock, category_id) VALUES('Llavero Flash', 70, 'https://http2.mlstatic.com/D_NQ_NP_855894-MLU74126714793_012024-O.webp', 46, 5);
INSERT INTO product(name, price, image, stock, category_id) VALUES('DC-MARVEL', 98.50, 'https://media.cnn.com/api/v1/images/stellar/prod/dcvsmarvelomni-adv-rev2-3-copy.jpg?q=w_1110,c_fill', 209, 3);
INSERT INTO product(name, price, image, stock, category_id) VALUES('Avengers Forever', 54.50, 'https://duncanvillebookstore.com/wp-content/uploads/2022/02/PR75960620192100321-3.jpg', 234, 3);
INSERT INTO movement(movement_date, type, user_id) VALUES('2024-07-01', 'INPUT', 6);
INSERT INTO movement_detail(quantity, product_id, movement_id) VALUES(100, 8, 23);
INSERT INTO movement_detail(quantity, product_id, movement_id) VALUES(50, 9, 23);
INSERT INTO movement(movement_date, type, user_id) VALUES('2024-07-01', 'INPUT', 6);
INSERT INTO movement_detail(quantity, product_id, movement_id) VALUES(70, 10, 26);
INSERT INTO movement_detail(quantity, product_id, movement_id) VALUES(23, 11, 26);
INSERT INTO movement(movement_date, type, user_id) VALUES('2024-07-01', 'INPUT', 6);
INSERT INTO movement_detail(quantity, product_id, movement_id) VALUES(98, 12, 29);
INSERT INTO movement_detail(quantity, product_id, movement_id) VALUES(50, 13, 29);
INSERT INTO movement_detail(quantity, product_id, movement_id) VALUES(40, 14, 29);
INSERT INTO movement(movement_date, type, user_id) VALUES('2024-07-01', 'INPUT', 6);
INSERT INTO movement_detail(quantity, product_id, movement_id) VALUES(23, 15, 33);
INSERT INTO movement_detail(quantity, product_id, movement_id) VALUES(12, 16, 33);
INSERT INTO movement_detail(quantity, product_id, movement_id) VALUES(200, 17, 33);
INSERT INTO movement_detail(quantity, product_id, movement_id) VALUES(102, 18, 33);
INSERT INTO movement(movement_date, type, user_id) VALUES('2024-07-02', 'INPUT', 6);
INSERT INTO movement_detail(quantity, product_id, movement_id) VALUES(235, 19, 38);
INSERT INTO movement_detail(quantity, product_id, movement_id) VALUES(56, 20, 38);
INSERT INTO movement(movement_date, type, user_id) VALUES('2024-07-02', 'INPUT', 6);
INSERT INTO movement_detail(quantity, product_id, movement_id) VALUES(209, 21, 41);
INSERT INTO movement_detail(quantity, product_id, movement_id) VALUES(234, 22, 41);
INSERT INTO movement(movement_date, type, user_id) VALUES('2024-07-02', 'OUTPUT', 6);
INSERT INTO movement_detail(quantity, product_id, movement_id) VALUES(10, 20, 44);
